# Site settings
title: "soft web"
description: "… is the research-driven and community-centered design practice of josh osborne and julia dann."
version: "0.1"
size: "20k"
announcement: "FIRST DAY OF CLASS IS WEDNESDAY AUG 24 9AM POLLAK 315"

# github pages deployment
# url: https://joshosbrn.github.io
# baseurl: softweb.world

# Build settings
markdown: kramdown

# Exclude this stuff
exclude: [node_modules, gulpfile.js, package-lock.json, package.json, Gemfile.lock, Gemfile, README.md]

# Gems
gems:
  - jekyll-seo-tag

# Analytics
ga: UA-42682851-7
