# Site settings
title: "soft web"
description: "… is the research-based and community-driven design practice of josh osborne and julia dann."
version: "0.1"
size: "20k"

# Build settings
markdown: kramdown

# Exclude this stuff
exclude: [node_modules, gulpfile.js, package-lock.json, package.json, Gemfile.lock, Gemfile, README.md]

# Gems
gems:
  - jekyll-seo-tag

# Analytics
ga: UA-42682851-7
